### ISSUE TITLE
Fill color as not ColorLong for android API < 26

### ISSUE THREAD

**Issue by Equin** [feiyin0719/AFreeSvg#30]
@feiyin0719 Hi can you change fill color type to ColorInt ? 
or maybe there is a way to convert int color to long color?
because right now on api 23 i cant  do it, Color.pack(), or other convert functions not supporter before API 26

**Comment by Equin** [comment]
@feiyin0719 any chanche this can be changed?

**Comment by Equin** [comment]
@feiyin0719  made PR here https://github.com/feiyin0719/AFreeSvg/pull/31

**Comment by feiyin0719** [comment]
ok, I have approved it, thanks

**Comment by Equin** [comment]
@feiyin0719 thanks =)
